version: '3'

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    volumes:
      - miniodata:/data

  spark-master:
    image: aco99/sparkmaster
    container_name: spark-master
    ports:
      - 4040:4040
      - 8080:8080
      - 7077:7077
    environment:
      - PYSPARK_PYTHON=python3
    volumes:
      - ./run.py:/spark/run.py

  spark-worker1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081

volumes:
  miniodata:
